In [1]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
from IPython.core.display import HTML
import numpy as np

In [2]:
eng_1011 = 'https://www.soccerassociation.com/0/1011/index.htm'
eng_1112 = 'https://www.soccerassociation.com/0/1112/index.htm'
eng_1213 = 'https://www.soccerassociation.com/0/1213/index.htm'
eng_1314 = 'https://www.soccerassociation.com/0/1314/index.htm'
eng_1415 = 'https://www.soccerassociation.com/0/1415/index.htm'
eng_1516 = 'https://www.soccerassociation.com/0/1516/index.htm'
eng_1617 = 'https://www.soccerassociation.com/0/1617/index.htm'
eng_1718 = 'https://www.soccerassociation.com/0/1718/index.htm'
eng_1819 = 'https://www.soccerassociation.com/0/1819/index.htm'
fra_1011 = 'https://www.soccerassociation.com/8/1011/index.htm'
fra_1112 = 'https://www.soccerassociation.com/8/1112/index.htm'
fra_1213 = 'https://www.soccerassociation.com/8/1213/index.htm'
fra_1314 = 'https://www.soccerassociation.com/8/1314/index.htm'
fra_1415 = 'https://www.soccerassociation.com/8/1415/index.htm'
fra_1516 = 'https://www.soccerassociation.com/8/1516/index.htm'
fra_1617 = 'https://www.soccerassociation.com/8/1617/index.htm'
fra_1718 = 'https://www.soccerassociation.com/8/1718/index.htm'
fra_1819 = 'https://www.soccerassociation.com/8/1819/index.htm'
ger_1011 = 'https://www.soccerassociation.com/32/1011/index.htm'
ger_1112 = 'https://www.soccerassociation.com/32/1112/index.htm'
ger_1213 = 'https://www.soccerassociation.com/32/1213/index.htm'
ger_1314 = 'https://www.soccerassociation.com/32/1314/index.htm'
ger_1415 = 'https://www.soccerassociation.com/32/1415/index.htm'
ger_1516 = 'https://www.soccerassociation.com/32/1516/index.htm'
ger_1617 = 'https://www.soccerassociation.com/32/1617/index.htm'
ger_1718 = 'https://www.soccerassociation.com/32/1718/index.htm'
ger_1819 = 'https://www.soccerassociation.com/32/1819/index.htm'
ita_1011 = 'https://www.soccerassociation.com/2/1011/index.htm'
ita_1112 = 'https://www.soccerassociation.com/2/1112/index.htm'
ita_1213 = 'https://www.soccerassociation.com/2/1213/index.htm'
ita_1314 = 'https://www.soccerassociation.com/2/1314/index.htm'
ita_1415 = 'https://www.soccerassociation.com/2/1415/index.htm'
ita_1516 = 'https://www.soccerassociation.com/2/1516/index.htm'
ita_1617 = 'https://www.soccerassociation.com/2/1617/index.htm'
ita_1718 = 'https://www.soccerassociation.com/2/1718/index.htm'
ita_1819 = 'https://www.soccerassociation.com/2/1819/index.htm'
spa_1011 = 'https://www.soccerassociation.com/9/1011/index.htm'
spa_1112 = 'https://www.soccerassociation.com/9/1112/index.htm'
spa_1213 = 'https://www.soccerassociation.com/9/1213/index.htm'
spa_1314 = 'https://www.soccerassociation.com/9/1314/index.htm'
spa_1415 = 'https://www.soccerassociation.com/9/1415/index.htm'
spa_1516 = 'https://www.soccerassociation.com/9/1516/index.htm'
spa_1617 = 'https://www.soccerassociation.com/9/1617/index.htm'
spa_1718 = 'https://www.soccerassociation.com/9/1718/index.htm'
spa_1819 = 'https://www.soccerassociation.com/9/1819/index.htm'

In [3]:
resulteng_1011 = requests.get(eng_1011)
resulteng_1011.status_code

200

In [4]:
resulteng_1011.content

b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head><title>England football league tables</title><link rel="stylesheet" type="text/css" href="/style.css?v=2.019"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="description" content=" football league tables with club info, squad, transfers, results, fixtures and statistics."><meta name="keywords" content="league table,latest standings,baltic cup,super cup,uefa under-21,nations cup,199900=emirates cup%201415=arabian gulf cup,caribbean cup,kupa,fa cup,199900=division 2%200405=league 1,kup crne gore,copa colombia,world cup,magyar kupa,superkarikas,kup bih,world cup,super cup,copa mercosur,irish cup,liigacup,kirin cup,superkubok,supa 8,beker van belgi\xc3\xab,east asian cup,international,suomen cup,troph\xc3\xa9e des champions,super pokal,kypello,kypello,valparaiso tournament,ta\xc3\xa7a da liga,199900=club world championship%200607=club world cup,recopa,nations league,euro,199900=division 3%200405=league 2,qatar stars cup,league cup,league cup,us cup,svenska cupen,state cup,dubai tournament,world cup,deildabikar,supercopa,knockout cup,thailand champions cup,copa venezuela,conference south,world cup,hrvatski kup,dfb pokal,norgesmesterskapet,199900=league cup%201617=efl cup,superkupa,fai cup,kup srbije,cup,aspida,sakartvelos tasi,concacaf champions league,bikar,supercup,copa mx,copa libertadores,super cup,oman tournament"><script type="text/javascript" src="/js.js"></script></head><body bgcolor="#ffffff" onLoad="time24(\'latest\')" text="#000000" link="#000000" vlink="#000000" alink="#000000"><table width="100%"><script type="text/javascript"><!--\na1();\n//--></script></table><a name="top"></a><table cellspacing=0 cellpadding=0 border=0 width="100%"><tr><td align=center><table><tr><td colspan=4 align=center></td><td valign=top><table border=0 cellspacing=0 cellpadding=0><tr><td align=center><table border=0 cellpadding=0 cellspacing=0><tr><td align=center><div class="fll"><a href="/72/index.htm"><img src="/flags/72.GIF" hspace=1 height=18 width=22 border=1 alt="ALB flag"><br><div>ALB</div></a></div></td><td align=center><div class="fll"><a href="/58/index.htm"><img src="/flags/58.GIF" hspace=1 height=18 width=22 border=1 alt="ALG flag"><br><div>ALG</div></a></div></td><td align=center><div class="fll"><a href="/24/index.htm"><img src="/flags/24.GIF" hspace=1 height=18 width=22 border=1 alt="ARG flag"><br><div>ARG</div></a></div></td><td align=center><div class="fll"><a href="/109/index.htm"><img src="/flags/109.GIF" hspace=1 height=18 width=22 border=1 alt="ARM flag"><br><div>ARM</div></a></div></td><td align=center><div class="fll"><a href="/33/index.htm"><img src="/flags/33.GIF" hspace=1 height=18 width=22 border=1 alt="AUS flag"><br><div>AUS</div></a></div></td><td align=center><div class="fll"><a href="/27/index.htm"><img src="/flags/27.GIF" hspace=1 height=18 width=22 border=1 alt="AUT flag"><br><div>AUT</div></a></div></td><td align=center><div class="fll"><a href="/95/index.htm"><img src="/flags/95.GIF" hspace=1 height=18 width=22 border=1 alt="AZE flag"><br><div>AZE</div></a></div></td><td align=center><div class="fll"><a href="/29/index.htm"><img src="/flags/29.GIF" hspace=1 height=18 width=22 border=1 alt="BEL flag"><br><div>BEL</div></a></div></td><td align=center><div class="fll"><a href="/51/index.htm"><img src="/flags/51.GIF" hspace=1 height=18 width=22 border=1 alt="BIH flag"><br><div>BIH</div></a></div></td><td align=center><div class="fll"><a href="/56/index.htm"><img src="/flags/56.GIF" hspace=1 height=18 width=22 border=1 alt="BLR flag"><br><div>BLR</div></a></div></td><td align=center><div class="fll"><a href="/49/index.htm"><img src="/flags/49.GIF" hspace=1 height=18 width=22 border=1 alt="BOL flag"><br><div>BOL</div></a></div></td><td align=center><div class="fll"><a href="/23/index.htm"><img src="/flags/23.GIF" hspace=1 height=18 width=22 border=1 alt="BRA flag"><br><div>BRA</div></a></div></td><td align=center><div class="fll"><a href="/43/index.htm"><img src="/flags/43.GIF" hspace=1 height=18 width=22 border=1 alt="BUL flag"><br><div>BUL</div></a></div></td><td align=center><div class="fll"><a href="/47/index.htm"><img src="/flags/47.GIF" hspace=1 height=18 width=22 border=1 alt="CHI flag"><br><div>CHI</div></a></div></td><td align=center><div class="fll"><a href="/97/index.htm"><img src="/flags/97.GIF" hspace=1 height=18 width=22 border=1 alt="CHN flag"><br><div>CHN</div></a></div></td><td align=center><div class="fll"><a href="/37/index.htm"><img src="/flags/37.GIF" hspace=1 height=18 width=22 border=1 alt="COL flag"><br><div>COL</div></a></div></td><td align=center><div class="fll"><a href="/104/index.htm"><img src="/flags/104.GIF" hspace=1 height=18 width=22 border=1 alt="CRC flag"><br><div>CRC</div></a></div></td><td align=center><div class="fll"><a href="/7/index.htm"><img src="/flags/7.GIF" hspace=1 height=18 width=22 border=1 alt="CRO flag"><br><div>CRO</div></a></div></td><td align=center><div class="fll"><a href="/39/index.htm"><img src="/flags/39.GIF" hspace=1 height=18 width=22 border=1 alt="CYP flag"><br><div>CYP</div></a></div></td><td align=center><div class="fll"><a href="/6/index.htm"><img src="/flags/6.GIF" hspace=1 height=18 width=22 border=1 alt="CZE flag"><br><div>CZE</div></a></div></td><td align=center><div class="fll"><a href="/11/index.htm"><img src="/flags/11.GIF" hspace=1 height=18 width=22 border=1 alt="DEN flag"><br><div>DEN</div></a></div></td><td align=center><div class="fll"><a href="/102/index.htm"><img src="/flags/102.GIF" hspace=1 height=18 width=22 border=1 alt="ECU flag"><br><div>ECU</div></a></div></td><td align=center><div class="fll"><a href="/4/index.htm"><img src="/flags/4.GIF" hspace=1 height=18 width=22 border=1 alt="EGY flag"><br><div>EGY</div></a></div></td></table><tr><td align=center><table border=0 cellpadding=0 cellspacing=0><tr><td align=center><div class="fll"><a href="/0/index.htm"><img src="/flags/0.GIF" hspace=1 height=18 width=22 border=1 alt="ENG flag"><br><div>ENG</div></a></div></td><td align=center><div class="fll"><a href="/9/index.htm"><img src="/flags/9.GIF" hspace=1 height=18 width=22 border=1 alt="ESP flag"><br><div>ESP</div></a></div></td><td align=center><div class="fll"><a href="/60/index.htm"><img src="/flags/60.GIF" hspace=1 height=18 width=22 border=1 alt="EST flag"><br><div>EST</div></a></div></td><td align=center><div class="fll"><a href="/21/index.htm"><img src="/flags/21.GIF" hspace=1 height=18 width=22 border=1 alt="FIN flag"><br><div>FIN</div></a></div></td><td align=center><div class="fll"><a href="/8/index.htm"><img src="/flags/8.GIF" hspace=1 height=18 width=22 border=1 alt="FRA flag"><br><div>FRA</div></a></div></td><td align=center><div class="fll"><a href="/55/index.htm"><img src="/flags/55.GIF" hspace=1 height=18 width=22 border=1 alt="GEO flag"><br><div>GEO</div></a></div></td><td align=center><div class="fll"><a href="/32/index.htm"><img src="/flags/32.GIF" hspace=1 height=18 width=22 border=1 alt="GER flag"><br><div>GER</div></a></div></td><td align=center><div class="fll"><a href="/20/index.htm"><img src="/flags/20.GIF" hspace=1 height=18 width=22 border=1 alt="GRE flag"><br><div>GRE</div></a></div></td><td align=center><div class="fll"><a href="/30/index.htm"><img src="/flags/30.GIF" hspace=1 height=18 width=22 border=1 alt="HUN flag"><br><div>HUN</div></a></div></td><td align=center><div class="fll"><a href="/16/index.htm"><img src="/flags/16.GIF" hspace=1 height=18 width=22 border=1 alt="IRL flag"><br><div>IRL</div></a></div></td><td align=center><div class="fll"><a href="/106/index.htm"><img src="/flags/106.GIF" hspace=1 height=18 width=22 border=1 alt="IRN flag"><br><div>IRN</div></a></div></td><td align=center><div class="fll"><a href="/34/index.htm"><img src="/flags/34.GIF" hspace=1 height=18 width=22 border=1 alt="ISL flag"><br><div>ISL</div></a></div></td><td align=center><div class="fll"><a href="/78/index.htm"><img src="/flags/78.GIF" hspace=1 height=18 width=22 border=1 alt="ISR flag"><br><div>ISR</div></a></div></td><td align=center><div class="fll"><a href="/2/index.htm"><img src="/flags/2.GIF" hspace=1 height=18 width=22 border=1 alt="ITA flag"><br><div>ITA</div></a></div></td><td align=center><div class="fll"><a href="/42/index.htm"><img src="/flags/42.GIF" hspace=1 height=18 width=22 border=1 alt="JPN flag"><br><div>JPN</div></a></div></td><td align=center><div class="fll"><a href="/111/index.htm"><img src="/flags/111.GIF" hspace=1 height=18 width=22 border=1 alt="KAZ flag"><br><div>KAZ</div></a></div></td><td align=center><div class="fll"><a href="/35/index.htm"><img src="/flags/35.GIF" hspace=1 height=18 width=22 border=1 alt="KOR flag"><br><div>KOR</div></a></div></td><td align=center><div class="fll"><a href="/59/index.htm"><img src="/flags/59.GIF" hspace=1 height=18 width=22 border=1 alt="LTU flag"><br><div>LTU</div></a></div></td><td align=center><div class="fll"><a href="/93/index.htm"><img src="/flags/93.GIF" hspace=1 height=18 width=22 border=1 alt="LVA flag"><br><div>LVA</div></a></div></td><td align=center><div class="fll"><a href="/90/index.htm"><img src="/flags/90.GIF" hspace=1 height=18 width=22 border=1 alt="MDA flag"><br><div>MDA</div></a></div></td><td align=center><div class="fll"><a href="/38/index.htm"><img src="/flags/38.GIF" hspace=1 height=18 width=22 border=1 alt="MEX flag"><br><div>MEX</div></a></div></td><td align=center><div class="fll"><a href="/74/index.htm"><img src="/flags/74.GIF" hspace=1 height=18 width=22 border=1 alt="MKD flag"><br><div>MKD</div></a></div></td><td align=center><div class="fll"><a href="/40/index.htm"><img src="/flags/40.GIF" hspace=1 height=18 width=22 border=1 alt="MLT flag"><br><div>MLT</div></a></div></td></table><tr><td align=center><table border=0 cellpadding=0 cellspacing=0><tr><td align=center><div class="fll"><a href="/210/index.htm"><img src="/flags/210.GIF" hspace=1 height=18 width=22 border=1 alt="MNE flag"><br><div>MNE</div></a></div></td><td align=center><div class="fll"><a href="/10/index.htm"><img src="/flags/10.GIF" hspace=1 height=18 width=22 border=1 alt="NED flag"><br><div>NED</div></a></div></td><td align=center><div class="fll"><a href="/15/index.htm"><img src="/flags/15.GIF" hspace=1 height=18 width=22 border=1 alt="NIR flag"><br><div>NIR</div></a></div></td><td align=center><div class="fll"><a href="/13/index.htm"><img src="/flags/13.GIF" hspace=1 height=18 width=22 border=1 alt="NOR flag"><br><div>NOR</div></a></div></td><td align=center><div class="fll"><a href="/92/index.htm"><img src="/flags/92.GIF" hspace=1 height=18 width=22 border=1 alt="PAR flag"><br><div>PAR</div></a></div></td><td align=center><div class="fll"><a href="/87/index.htm"><img src="/flags/87.GIF" hspace=1 height=18 width=22 border=1 alt="PER flag"><br><div>PER</div></a></div></td><td align=center><div class="fll"><a href="/28/index.htm"><img src="/flags/28.GIF" hspace=1 height=18 width=22 border=1 alt="POL flag"><br><div>POL</div></a></div></td><td align=center><div class="fll"><a href="/17/index.htm"><img src="/flags/17.GIF" hspace=1 height=18 width=22 border=1 alt="POR flag"><br><div>POR</div></a></div></td><td align=center><div class="fll"><a href="/138/index.htm"><img src="/flags/138.GIF" hspace=1 height=18 width=22 border=1 alt="QAT flag"><br><div>QAT</div></a></div></td><td align=center><div class="fll"><a href="/19/index.htm"><img src="/flags/19.GIF" hspace=1 height=18 width=22 border=1 alt="ROU flag"><br><div>ROU</div></a></div></td><td align=center><div class="fll"><a href="/5/index.htm"><img src="/flags/5.GIF" hspace=1 height=18 width=22 border=1 alt="RSA flag"><br><div>RSA</div></a></div></td><td align=center><div class="fll"><a href="/31/index.htm"><img src="/flags/31.GIF" hspace=1 height=18 width=22 border=1 alt="RUS flag"><br><div>RUS</div></a></div></td><td align=center><div class="fll"><a href="/12/index.htm"><img src="/flags/12.GIF" hspace=1 height=18 width=22 border=1 alt="SCO flag"><br><div>SCO</div></a></div></td><td align=center><div class="fll"><a href="/94/index.htm"><img src="/flags/94.GIF" hspace=1 height=18 width=22 border=1 alt="SRB flag"><br><div>SRB</div></a></div></td><td align=center><div class="fll"><a href="/18/index.htm"><img src="/flags/18.GIF" hspace=1 height=18 width=22 border=1 alt="SUI flag"><br><div>SUI</div></a></div></td><td align=center><div class="fll"><a href="/98/index.htm"><img src="/flags/98.GIF" hspace=1 height=18 width=22 border=1 alt="SVK flag"><br><div>SVK</div></a></div></td><td align=center><div class="fll"><a href="/46/index.htm"><img src="/flags/46.GIF" hspace=1 height=18 width=22 border=1 alt="SVN flag"><br><div>SVN</div></a></div></td><td align=center><div class="fll"><a href="/22/index.htm"><img src="/flags/22.GIF" hspace=1 height=18 width=22 border=1 alt="SWE flag"><br><div>SWE</div></a></div></td><td align=center><div class="fll"><a href="/41/index.htm"><img src="/flags/41.GIF" hspace=1 height=18 width=22 border=1 alt="TUR flag"><br><div>TUR</div></a></div></td><td align=center><div class="fll"><a href="/36/index.htm"><img src="/flags/36.GIF" hspace=1 height=18 width=22 border=1 alt="UKR flag"><br><div>UKR</div></a></div></td><td align=center><div class="fll"><a href="/25/index.htm"><img src="/flags/25.GIF" hspace=1 height=18 width=22 border=1 alt="URU flag"><br><div>URU</div></a></div></td><td align=center><div class="fll"><a href="/26/index.htm"><img src="/flags/26.GIF" hspace=1 height=18 width=22 border=1 alt="USA flag"><br><div>USA</div></a></div></td><td align=center><div class="fll"><a href="/105/index.htm"><img src="/flags/105.GIF" hspace=1 height=18 width=22 border=1 alt="VEN flag"><br><div>VEN</div></a></div></td></table></table></td><td valign=top><table border=0 cellspacing=0 cellpadding=0><tr><td align=right><a class="fc" href="/home.htm">home</a><img src="/images/lf.gif" height=8 width=8 hspace=2><tr><td align=right><a class="fc" href="https://www.soccerassociation.com/cgi-bin/sub.cgi">account</a><img src="/images/lf.gif" height=8 width=8 hspace=2><tr><td align=right><a class="fc" href="javascript:help()">help</a><img src="/images/lf.gif" height=8 width=8 hspace=2><tr><td align=right><a class="fc" href="/cgi-bin/feedback.cgi">support</a><img src="/images/lf.gif" height=8 width=8 hspace=2><script type="text/javascript"><!--\nlg();\n//--></script></tr><form name="tme" action="#"><tr><td align=right><input class="tfh" type=text name="tfh" size=4 readonly></tr></form></table></td><td valign=top><img src="/images/sa100.gif" alt="SA logo" height=100></td><td valign=top><form method="post" action="/cgi-bin/search.cgi"><table width="100%" border=0 cellspacing=0 cellpadding=0><tr><td colspan=2><tr><td colspan=2><img src="/images/same.gif" alt="" height=8 width=8 hspace=2><a class="fc" href="/faq.htm">FAQ</a><tr><td colspan=2><img src="/images/same.gif" alt="" height=8 width=8 hspace=2><a class="fc" href="/cgi-bin/az.cgi">A to Z</a><tr><td><br><input onFocus="if(this.value==\'name search\'){this.value=\'\';}" type=text size=11 maxlength=16 class="ps" name="ps" value="name search"><tr><td><select name="p"><option value="p">player<option value="c">club<option value="r">referee<option value="m">manager</select>&nbsp;<input type=submit value="go>>" class="b"></table></tr></form></table><tr><td width="100%" valign=top align=center><table cellspacing=0 cellpadding=0 border=0><div class="T9B taC"><img src="/flags/0.GIF" height=20 width=28 class="flag m0x4">Latest<img src="/flags/0.GIF" height=20 width=28 class="flag m0x4"></div><tr><td align=center><div class="b f120"><a href="/0/1011/index0.htm">Premier League</a> | <a href="/0/1011/index1.htm">Championship</a> | <a href="/0/1011/index2.htm">League 1</a> | <a href="/0/1011/index3.htm">League 2</a> | <a href="/0/1011/index4.htm">Conference National</a> | <img border=1 class="flag m0x2" width=15 height=12 src="/flags/0.GIF"><a href="/sqp/0/index.htm">squads</a> | <img border=1 class="flag m0x2" width=15 height=12 src="/flags/0.GIF"><a href="/0/cups.htm">cups</a></div><br><a name="archive"></a><table class="tb2p2 mC"><tr><td class="title taC">Season archive</td><td class="bgE"><select name="prs" id="prs"><option value="1920">2019/20<option value="1819">2018/19<option value="1718">2017/18<option value="1617">2016/17<option value="1516">2015/16<option value="1415">2014/15<option value="1314">2013/14<option value="1213">2012/13<option value="1112">2011/12<option value="0910">2009/10<option value="0809">2008/09<option value="0708">2007/08<option value="0607">2006/07<option value="0506">2005/06<option value="0405">2004/05<option value="0304">2003/04<option value="0203">2002/03<option value="0102">2001/02<option value="0001">2000/01<option value="9900">1999/00</select> <input type=button class="b" value="view >" onClick="location.href=\'/0/\'+document.getElementById(\'prs\').value+\'/index.htm\'"></table><br><div class="taC club">Season 2010/11</div><tr><td align=center valign=top><br><a name="league table"></a><table cellspacing=0 border=0 cellpadding=0><tr><td width="4"><br></td><td align=right valign=top><img align=right hspace=0 vspace=4 src="/images/titles/0+0.gif" border=0></td><td valign=top><table class="qtabw"><tr><td class="vaT"><table class="qtab"><tr bgcolor="#ddddff"><td width="10"></td><td width=1>1</td><td width="16" align=right><br></td><td nowrap align=left><a href="/cgi-bin/info.cgi?0/47/manchesterunited"><b>Manchester United</b></a></td><td><b>80</b><tr bgcolor="#ffffff"><td></td><td width=1>2</td><td><br></td><td align=left><a href="/cgi-bin/info.cgi?0/20/chelsea"><b>Chelsea</b></a></td><td><b>71</b><tr bgcolor="#ddddff"><td></td><td width=1>3</td><td><br></td><td nowrap align=left><a href="/cgi-bin/info.cgi?0/46/manchestercity"><b>Manchester City</b></a></td><td><b>71</b><tr bgcolor="#ffffff"><td></td><td width=1>4</td><td><br></td><td align=left><a href="/cgi-bin/info.cgi?0/0/arsenal"><b>Arsenal</b></a></td><td><b>68</b><tr bgcolor="#ddddff"><td></td><td width=1>5</td><td><br></td><td nowrap align=left><a href="/cgi-bin/info.cgi?0/80/tottenhamhotspur"><b>Tottenham Hotspur</b></a></td><td><b>62</b><tr bgcolor="#ffffff"><td></td><td width=1>6</td><td><br></td><td align=left><a href="/cgi-bin/info.cgi?0/44/liverpool"><b>Liverpool</b></a></td><td><b>58</b><tr bgcolor="#ddddff"><td></td><td width=1>7</td><td><br></td><td align=left><a href="/cgi-bin/info.cgi?0/30/everton"><b>Everton</b></a></td><td><b>54</b><tr bgcolor="#ffffff"><td></td><td width=1>8</td><td><br></td><td align=left><a href="/cgi-bin/info.cgi?0/32/fulham"><b>Fulham</b></a></td><td><b>49</b><tr bgcolor="#ddddff"><td></td><td width=1>9</td><td><br></td><td nowrap align=left><a href="/cgi-bin/info.cgi?0/1/astonvilla"><b>Aston Villa</b></a></td><td><b>48</b><tr bgcolor="#ffffff"><td></td><td width=1>10</td><td><br></td><td align=left><a href="/cgi-bin/info.cgi?0/76/sunderland"><b>Sunderland</b></a></td><td><b>47</b><tr bgcolor="#ddddff"><td></td><td width=1>11</td><td><br></td><td align=left><a href="/cgi-bin/info.cgi?0/84/wba"><b>WBA</b></a></td><td><b>47</b><tr bgcolor="#ffffff"><td></td><td width=1>12</td><td><br></td><td nowrap align=left><a href="/cgi-bin/info.cgi?0/51/newcastleunited"><b>Newcastle United</b></a></td><td><b>46</b><tr bgcolor="#ddddff"><td></td><td width=1>13</td><td><br></td><td nowrap align=left><a href="/cgi-bin/info.cgi?0/75/stokecity"><b>Stoke City</b></a></td><td><b>46</b><tr bgcolor="#ffffff"><td></td><td width=1>14</td><td><br></td><td nowrap align=left><a href="/cgi-bin/info.cgi?0/7/boltonwanderers"><b>Bolton Wanderers</b></a></td><td><b>46</b><tr bgcolor="#ddddff"><td></td><td width=1>15</td><td><br></td><td nowrap align=left><a href="/cgi-bin/info.cgi?0/5/blackburnrovers"><b>Blackburn Rovers</b></a></td><td><b>43</b><tr bgcolor="#ffffff"><td></td><td width=1>16</td><td><br></td><td nowrap align=left><a href="/cgi-bin/info.cgi?0/86/wiganathletic"><b>Wigan Athletic</b></a></td><td><b>42</b><tr bgc

In [5]:
req_code = requests.get(eng_1011)
soup_code = bs(req_code.content)
#league_table = pd.read_html(str(soup_code))[0]

In [6]:
soup_code

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><head><title>England football league tables</title><link href="/style.css?v=2.019" rel="stylesheet" type="text/css"/><meta content="text/html; charset=utf-8" http-equiv="Content-Type"/><meta content=" football league tables with club info, squad, transfers, results, fixtures and statistics." name="description"/><meta content="league table,latest standings,baltic cup,super cup,uefa under-21,nations cup,199900=emirates cup%201415=arabian gulf cup,caribbean cup,kupa,fa cup,199900=division 2%200405=league 1,kup crne gore,copa colombia,world cup,magyar kupa,superkarikas,kup bih,world cup,super cup,copa mercosur,irish cup,liigacup,kirin cup,superkubok,supa 8,beker van belgië,east asian cup,international,suomen cup,trophée des champions,super pokal,kypello,kypello,valparaiso tournament,taça da liga,199900=club world championship%200607=club world cup,recopa,nations league,euro,199900=division 3%200405=league 2,qatar stars cup,league cup,league cup,us cup,svenska cupen,state cup,dubai tournament,world cup,deildabikar,supercopa,knockout cup,thailand champions cup,copa venezuela,conference south,world cup,hrvatski kup,dfb pokal,norgesmesterskapet,199900=league cup%201617=efl cup,superkupa,fai cup,kup srbije,cup,aspida,sakartvelos tasi,concacaf champions league,bikar,supercup,copa mx,copa libertadores,super cup,oman tournament" name="keywords"/><script src="/js.js" type="text/javascript"></script></head><body alink="#000000" bgcolor="#ffffff" link="#000000" onload="time24('latest')" text="#000000" vlink="#000000"><table width="100%"><script type="text/javascript"><!--
a1();
//--></script></table><a name="top"></a><table border="0" cellpadding="0" cellspacing="0" width="100%"><tr><td align="center"><table><tr><td align="center" colspan="4"></td><td valign="top"><table border="0" cellpadding="0" cellspacing="0"><tr><td align="center"><table border="0" cellpadding="0" cellspacing="0"><tr><td align="center"><div class="fll"><a href="/72/index.htm"><img alt="ALB flag" border="1" height="18" hspace="1" src="/flags/72.GIF" width="22"/><br/><div>ALB</div></a></div></td><td align="center"><div class="fll"><a href="/58/index.htm"><img alt="ALG flag" border="1" height="18" hspace="1" src="/flags/58.GIF" width="22"/><br/><div>ALG</div></a></div></td><td align="center"><div class="fll"><a href="/24/index.htm"><img alt="ARG flag" border="1" height="18" hspace="1" src="/flags/24.GIF" width="22"/><br/><div>ARG</div></a></div></td><td align="center"><div class="fll"><a href="/109/index.htm"><img alt="ARM flag" border="1" height="18" hspace="1" src="/flags/109.GIF" width="22"/><br/><div>ARM</div></a></div></td><td align="center"><div class="fll"><a href="/33/index.htm"><img alt="AUS flag" border="1" height="18" hspace="1" src="/flags/33.GIF" width="22"/><br/><div>AUS</div></a></div></td><td align="center"><div class="fll"><a href="/27/index.htm"><img alt="AUT flag" border="1" height="18" hspace="1" src="/flags/27.GIF" width="22"/><br/><div>AUT</div></a></div></td><td align="center"><div class="fll"><a href="/95/index.htm"><img alt="AZE flag" border="1" height="18" hspace="1" src="/flags/95.GIF" width="22"/><br/><div>AZE</div></a></div></td><td align="center"><div class="fll"><a href="/29/index.htm"><img alt="BEL flag" border="1" height="18" hspace="1" src="/flags/29.GIF" width="22"/><br/><div>BEL</div></a></div></td><td align="center"><div class="fll"><a href="/51/index.htm"><img alt="BIH flag" border="1" height="18" hspace="1" src="/flags/51.GIF" width="22"/><br/><div>BIH</div></a></div></td><td align="center"><div class="fll"><a href="/56/index.htm"><img alt="BLR flag" border="1" height="18" hspace="1" src="/flags/56.GIF" width="22"/><br/><div>BLR</div></a></div></td><td align="center"><div class="fll"><a href="/49/index.htm"><img alt="BOL flag" border="1" height="18" hspace="1" src="/flags/49.GIF" width="22"/><br/><div>BOL</div></a></div></td><td align="center"><div class="fll"><a href="/23/index.htm"><img alt="BRA flag" border="1" height="18" hspace="1" src="/flags/23.GIF" width="22"/><br/><div>BRA</div></a></div></td><td align="center"><div class="fll"><a href="/43/index.htm"><img alt="BUL flag" border="1" height="18" hspace="1" src="/flags/43.GIF" width="22"/><br/><div>BUL</div></a></div></td><td align="center"><div class="fll"><a href="/47/index.htm"><img alt="CHI flag" border="1" height="18" hspace="1" src="/flags/47.GIF" width="22"/><br/><div>CHI</div></a></div></td><td align="center"><div class="fll"><a href="/97/index.htm"><img alt="CHN flag" border="1" height="18" hspace="1" src="/flags/97.GIF" width="22"/><br/><div>CHN</div></a></div></td><td align="center"><div class="fll"><a href="/37/index.htm"><img alt="COL flag" border="1" height="18" hspace="1" src="/flags/37.GIF" width="22"/><br/><div>COL</div></a></div></td><td align="center"><div class="fll"><a href="/104/index.htm"><img alt="CRC flag" border="1" height="18" hspace="1" src="/flags/104.GIF" width="22"/><br/><div>CRC</div></a></div></td><td align="center"><div class="fll"><a href="/7/index.htm"><img alt="CRO flag" border="1" height="18" hspace="1" src="/flags/7.GIF" width="22"/><br/><div>CRO</div></a></div></td><td align="center"><div class="fll"><a href="/39/index.htm"><img alt="CYP flag" border="1" height="18" hspace="1" src="/flags/39.GIF" width="22"/><br/><div>CYP</div></a></div></td><td align="center"><div class="fll"><a href="/6/index.htm"><img alt="CZE flag" border="1" height="18" hspace="1" src="/flags/6.GIF" width="22"/><br/><div>CZE</div></a></div></td><td align="center"><div class="fll"><a href="/11/index.htm"><img alt="DEN flag" border="1" height="18" hspace="1" src="/flags/11.GIF" width="22"/><br/><div>DEN</div></a></div></td><td align="center"><div class="fll"><a href="/102/index.htm"><img alt="ECU flag" border="1" height="18" hspace="1" src="/flags/102.GIF" width="22"/><br/><div>ECU</div></a></div></td><td align="center"><div class="fll"><a href="/4/index.htm"><img alt="EGY flag" border="1" height="18" hspace="1" src="/flags/4.GIF" width="22"/><br/><div>EGY</div></a></div></td></tr></table></td></tr><tr><td align="center"><table border="0" cellpadding="0" cellspacing="0"><tr><td align="center"><div class="fll"><a href="/0/index.htm"><img alt="ENG flag" border="1" height="18" hspace="1" src="/flags/0.GIF" width="22"/><br/><div>ENG</div></a></div></td><td align="center"><div class="fll"><a href="/9/index.htm"><img alt="ESP flag" border="1" height="18" hspace="1" src="/flags/9.GIF" width="22"/><br/><div>ESP</div></a></div></td><td align="center"><div class="fll"><a href="/60/index.htm"><img alt="EST flag" border="1" height="18" hspace="1" src="/flags/60.GIF" width="22"/><br/><div>EST</div></a></div></td><td align="center"><div class="fll"><a href="/21/index.htm"><img alt="FIN flag" border="1" height="18" hspace="1" src="/flags/21.GIF" width="22"/><br/><div>FIN</div></a></div></td><td align="center"><div class="fll"><a href="/8/index.htm"><img alt="FRA flag" border="1" height="18" hspace="1" src="/flags/8.GIF" width="22"/><br/><div>FRA</div></a></div></td><td align="center"><div class="fll"><a href="/55/index.htm"><img alt="GEO flag" border="1" height="18" hspace="1" src="/flags/55.GIF" width="22"/><br/><div>GEO</div></a></div></td><td align="center"><div class="fll"><a href="/32/index.htm"><img alt="GER flag" border="1" height="18" hspace="1" src="/flags/32.GIF" width="22"/><br/><div>GER</div></a></div></td><td align="center"><div class="fll"><a href="/20/index.htm"><img alt="GRE flag" border="1" height="18" hspace="1" src="/flags/20.GIF" width="22"/><br/><div>GRE</div></a></div></td><td align="center"><div class="fll"><a href="/30/index.htm"><img alt="HUN flag" border="1" height="18" hspace="1" src="/flags/30.GIF" width="22"/><br/><div>HUN</div></a></div></td><td align="center"><div class="fll"><a href="/16/index.htm"><img alt="IRL flag" border="1" height="18" hspace="1" src="/flags/16.GIF" width="22"/><br/><div>IRL</div></a></div></td><td align="center"><div class="fll"><a href="/106/index.htm"><img alt="IRN flag" border="1" height="18" hspace="1" src="/flags/106.GIF" width="22"/><br/><div>IRN</div></a></div></td><td align="center"><div class="fll"><a href="/34/index.htm"><img alt="ISL flag" border="1" height="18" hspace="1" src="/flags/34.GIF" width="22"/><br/><div>ISL</div></a></div></td><td align="center"><div class="fll"><a href="/78/index.htm"><img alt="ISR flag" border="1" height="18" hspace="1" src="/flags/78.GIF" width="22"/><br/><div>ISR</div></a></div></td><td align="center"><div class="fll"><a href="/2/index.htm"><img alt="ITA flag" border="1" height="18" hspace="1" src="/flags/2.GIF" width="22"/><br/><div>ITA</div></a></div></td><td align="center"><div class="fll"><a href="/42/index.htm"><img alt="JPN flag" border="1" height="18" hspace="1" src="/flags/42.GIF" width="22"/><br/><div>JPN</div></a></div></td><td align="center"><div class="fll"><a href="/111/index.htm"><img alt="KAZ flag" border="1" height="18" hspace="1" src="/flags/111.GIF" width="22"/><br/><div>KAZ</div></a></div></td><td align="center"><div class="fll"><a href="/35/index.htm"><img alt="KOR flag" border="1" height="18" hspace="1" src="/flags/35.GIF" width="22"/><br/><div>KOR</div></a></div></td><td align="center"><div class="fll"><a href="/59/index.htm"><img alt="LTU flag" border="1" height="18" hspace="1" src="/flags/59.GIF" width="22"/><br/><div>LTU</div></a></div></td><td align="center"><div class="fll"><a href="/93/index.htm"><img alt="LVA flag" border="1" height="18" hspace="1" src="/flags/93.GIF" width="22"/><br/><div>LVA</div></a></div></td><td align="center"><div class="fll"><a href="/90/index.htm"><img alt="MDA flag" border="1" height="18" hspace="1" src="/flags/90.GIF" width="22"/><br/><div>MDA</div></a></div></td><td align="center"><div class="fll"><a href="/38/index.htm"><img alt="MEX flag" border="1" height="18" hspace="1" src="/flags/38.GIF" width="22"/><br/><div>MEX</div></a></div></td><td align="center"><div class="fll"><a href="/74/index.htm"><img alt="MKD flag" border="1" height="18" hspace="1" src="/flags/74.GIF" width="22"/><br/><div>MKD</div></a></div></td><td align="center"><div class="fll"><a href="/40/index.htm"><img alt="MLT flag" border="1" height="18" hspace="1" src="/flags/40.GIF" width="22"/><br/><div>MLT</div></a></div></td></tr></table></td></tr><tr><td align="center"><table border="0" cellpadding="0" cellspacing="0"><tr><td align="center"><div class="fll"><a href="/210/index.htm"><img alt="MNE flag" border="1" height="18" hspace="1" src="/flags/210.GIF" width="22"/><br/><div>MNE</div></a></div></td><td align="center"><div class="fll"><a href="/10/index.htm"><img alt="NED flag" border="1" height="18" hspace="1" src="/flags/10.GIF" width="22"/><br/><div>NED</div></a></div></td><td align="center"><div class="fll"><a href="/15/index.htm"><img alt="NIR flag" border="1" height="18" hspace="1" src="/flags/15.GIF" width="22"/><br/><div>NIR</div></a></div></td><td align="center"><div class="fll"><a href="/13/index.htm"><img alt="NOR flag" border="1" height="18" hspace="1" src="/flags/13.GIF" width="22"/><br/><div>NOR</div></a></div></td><td align="center"><div class="fll"><a href="/92/index.htm"><img alt="PAR flag" border="1" height="18" hspace="1" src="/flags/92.GIF" width="22"/><br/><div>PAR</div></a></div></td><td align="center"><div class="fll"><a href="/87/index.htm"><img alt="PER flag" border="1" height="18" hspace="1" src="/flags/87.GIF" width="22"/><br/><div>PER</div></a></div></td><td align="center"><div class="fll"><a href="/28/index.htm"><img alt="POL flag" border="1" height="18" hspace="1" src="/flags/28.GIF" width="22"/><br/><div>POL</div></a></div></td><td align="center"><div class="fll"><a href="/17/index.htm"><img alt="POR flag" border="1" height="18" hspace="1" src="/flags/17.GIF" width="22"/><br/><div>POR</div></a></div></td><td align="center"><div class="fll"><a href="/138/index.htm"><img alt="QAT flag" border="1" height="18" hspace="1" src="/flags/138.GIF" width="22"/><br/><div>QAT</div></a></div></td><td align="center"><div class="fll"><a href="/19/index.htm"><img alt="ROU flag" border="1" height="18" hspace="1" src="/flags/19.GIF" width="22"/><br/><div>ROU</div></a></div></td><td align="center"><div class="fll"><a href="/5/index.htm"><img alt="RSA flag" border="1" height="18" hspace="1" src="/flags/5.GIF" width="22"/><br/><div>RSA</div></a></div></td><td align="center"><div class="fll"><a href="/31/index.htm"><img alt="RUS flag" border="1" height="18" hspace="1" src="/flags/31.GIF" width="22"/><br/><div>RUS</div></a></div></td><td align="center"><div class="fll"><a href="/12/index.htm"><img alt="SCO flag" border="1" height="18" hspace="1" src="/flags/12.GIF" width="22"/><br/><div>SCO</div></a></div></td><td align="center"><div class="fll"><a href="/94/index.htm"><img alt="SRB flag" border="1" height="18" hspace="1" src="/flags/94.GIF" width="22"/><br/><div>SRB</div></a></div></td><td align="center"><div class="fll"><a href="/18/index.htm"><img alt="SUI flag" border="1" height="18" hspace="1" src="/flags/18.GIF" width="22"/><br/><div>SUI</div></a></div></td><td align="center"><div class="fll"><a href="/98/index.htm"><img alt="SVK flag" border="1" height="18" hspace="1" src="/flags/98.GIF" width="22"/><br/><div>SVK</div></a></div></td><td align="center"><div class="fll"><a href="/46/index.htm"><img alt="SVN flag" border="1" height="18" hspace="1" src="/flags/46.GIF" width="22"/><br/><div>SVN</div></a></div></td><td align="center"><div class="fll"><a href="/22/index.htm"><img alt="SWE flag" border="1" height="18" hspace="1" src="/flags/22.GIF" width="22"/><br/><div>SWE</div></a></div></td><td align="center"><div class="fll"><a href="/41/index.htm"><img alt="TUR flag" border="1" height="18" hspace="1" src="/flags/41.GIF" width="22"/><br/><div>TUR</div></a></div></td><td align="center"><div class="fll"><a href="/36/index.htm"><img alt="UKR flag" border="1" height="18" hspace="1" src="/flags/36.GIF" width="22"/><br/><div>UKR</div></a></div></td><td align="center"><div class="fll"><a href="/25/index.htm"><img alt="URU flag" border="1" height="18" hspace="1" src="/flags/25.GIF" width="22"/><br/><div>URU</div></a></div></td><td align="center"><div class="fll"><a href="/26/index.htm"><img alt="USA flag" border="1" height="18" hspace="1" src="/flags/26.GIF" width="22"/><br/><div>USA</div></a></div></td><td align="center"><div class="fll"><a href="/105/index.htm"><img alt="VEN flag" border="1" height="18" hspace="1" src="/flags/105.GIF" width="22"/><br/><div>VEN</div></a></div></td></tr></table></td></tr></table></td><td valign="top"><table border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><a class="fc" href="/home.htm">home</a><img height="8" hspace="2" src="/images/lf.gif" width="8"/></td></tr><tr><td align="right"><a class="fc" href="https://www.soccerassociation.com/cgi-bin/sub.cgi">account</a><img height="8" hspace="2" src="/images/lf.gif" width="8"/></td></tr><tr><td align="right"><a class="fc" href="javascript:help()">help</a><img height="8" hspace="2" src="/images/lf.gif" width="8"/></td></tr><tr><td align="right"><a class="fc" href="/cgi-bin/feedback.cgi">support</a><img height="8" hspace="2" src="/images/lf.gif" width="8"/><script type="text/javascript"><!--
lg();

In [7]:
pd.read_html(str(soup_code))[12]

     0   1   2                  3   4
0  NaN   1 NaN  Manchester United  80
1  NaN   2 NaN            Chelsea  71
2  NaN   3 NaN    Manchester City  71
3  NaN   4 NaN            Arsenal  68
4  NaN   5 NaN  Tottenham Hotspur  62
5  NaN   6 NaN          Liverpool  58
6  NaN   7 NaN            Everton  54
7  NaN   8 NaN             Fulham  49
8  NaN   9 NaN        Aston Villa  48
9  NaN  10 NaN         Sunderland  47
10 NaN  11 NaN                WBA  47
11 NaN  12 NaN   Newcastle United  46
12 NaN  13 NaN         Stoke City  46
13 NaN  14 NaN   Bolton Wanderers  46
14 NaN  15 NaN   Blackburn Rovers  43
15 NaN  16 NaN     Wigan Athletic  42
16 NaN  17 NaN             Wolves  40
17 NaN  18 NaN    Birmingham City  39
18 NaN  19 NaN          Blackpool  39
19 NaN  20 NaN    West Ham United  33

In [8]:
def create_league_table(url_base, season_years, league_name):
    result_code = requests.get(url_base)
    soup_code = bs(result_code.content)
    league_table = pd.read_html(str(soup_code))[12]
    league_table['season'] = season_years
    league_table['league_name'] = league_name
    return(league_table)

In [9]:
england_1011 = create_league_table(eng_1011, '2010/2011', 'English Premier League')
england_1112 = create_league_table(eng_1112, '2011/2012', 'English Premier League')
england_1213 = create_league_table(eng_1213, '2012/2013', 'English Premier League')
england_1314 = create_league_table(eng_1314, '2013/2014', 'English Premier League')
england_1415 = create_league_table(eng_1415, '2014/2015', 'English Premier League')
england_1516 = create_league_table(eng_1516, '2015/2016', 'English Premier League')
england_1617 = create_league_table(eng_1617, '2016/2017', 'English Premier League')
england_1718 = create_league_table(eng_1718, '2017/2018', 'English Premier League')
england_1819 = create_league_table(eng_1819, '2018/2019', 'English Premier League')
england_tables = pd.concat([england_1011, england_1112, england_1213, england_1314, england_1415, england_1516,
                           england_1617, england_1718, england_1819])

In [10]:
england_tables.head()

    0  1   2                  3   4     season             league_name
0 NaN  1 NaN  Manchester United  80  2010/2011  English Premier League
1 NaN  2 NaN            Chelsea  71  2010/2011  English Premier League
2 NaN  3 NaN    Manchester City  71  2010/2011  English Premier League
3 NaN  4 NaN            Arsenal  68  2010/2011  English Premier League
4 NaN  5 NaN  Tottenham Hotspur  62  2010/2011  English Premier League

In [11]:
france_1011 = create_league_table(fra_1011, '2010/2011', 'French Ligue 1')
france_1112 = create_league_table(fra_1112, '2011/2012', 'French Ligue 1')
france_1213 = create_league_table(fra_1213, '2012/2013', 'French Ligue 1')
france_1314 = create_league_table(fra_1314, '2013/2014', 'French Ligue 1')
france_1415 = create_league_table(fra_1415, '2014/2015', 'French Ligue 1')
france_1516 = create_league_table(fra_1516, '2015/2016', 'French Ligue 1')
france_1617 = create_league_table(fra_1617, '2016/2017', 'French Ligue 1')
france_1819 = create_league_table(fra_1819, '2018/2019', 'French Ligue 1')
france_tables = pd.concat([france_1011, france_1112, france_1213, france_1314, france_1415, france_1516,
                           france_1617, france_1819])

In [12]:
def create_french_outlier(url_base, season_years, league_name):
    result_code = requests.get(url_base)
    soup_code = bs(result_code.content)
    league_table = pd.read_html(str(soup_code))[10]
    league_table['season'] = season_years
    league_table['league_name'] = league_name
    return(league_table)

In [13]:
france_1718 = create_french_outlier(fra_1718, '2017/18', 'French Ligue 1')
france_tables = pd.concat([france_tables, france_1718])
france_tables.tail()

     0   1   2         3   4   season     league_name
15 NaN  16 NaN      Caen  38  2017/18  French Ligue 1
16 NaN  17 NaN     Lille  38  2017/18  French Ligue 1
17 NaN  18 NaN  Toulouse  37  2017/18  French Ligue 1
18 NaN  19 NaN    Troyes  33  2017/18  French Ligue 1
19 NaN  20 NaN      Metz  26  2017/18  French Ligue 1

In [14]:
germany_1011 = create_league_table(ger_1011, '2010/2011', 'German Bundesliga')
germany_1112 = create_league_table(ger_1112, '2011/2012', 'German Bundesliga')
germany_1213 = create_league_table(ger_1213, '2012/2013', 'German Bundesliga')
germany_1314 = create_league_table(ger_1314, '2013/2014', 'German Bundesliga')
germany_1415 = create_league_table(ger_1415, '2014/2015', 'German Bundesliga')
germany_1516 = create_league_table(ger_1516, '2015/2016', 'German Bundesliga')
germany_1617 = create_league_table(ger_1617, '2016/2017', 'German Bundesliga')
germany_1718 = create_league_table(ger_1718, '2017/2018', 'German Bundesliga')
germany_1819 = create_league_table(ger_1819, '2018/2019', 'German Bundesliga')
germany_tables = pd.concat([germany_1011, germany_1112, germany_1213, germany_1314, germany_1415, germany_1516,
                           germany_1617, germany_1718, germany_1819])
germany_tables.head()

    0  1   2                  3   4     season        league_name
0 NaN  1 NaN  Borussia Dortmund  75  2010/2011  German Bundesliga
1 NaN  2 NaN   Bayer Leverkusen  68  2010/2011  German Bundesliga
2 NaN  3 NaN     Bayern München  65  2010/2011  German Bundesliga
3 NaN  4 NaN        Hannover 96  60  2010/2011  German Bundesliga
4 NaN  5 NaN       FSV Mainz 05  58  2010/2011  German Bundesliga

In [15]:
italy_1011 = create_league_table(ita_1011, '2010/2011', 'Italian Serie A')
italy_1112 = create_league_table(ita_1112, '2011/2012', 'Italian Serie A')
italy_1213 = create_league_table(ita_1213, '2012/2013', 'Italian Serie A')
italy_1314 = create_league_table(ita_1314, '2013/2014', 'Italian Serie A')
italy_1415 = create_league_table(ita_1415, '2014/2015', 'Italian Serie A')
italy_1516 = create_league_table(ita_1516, '2015/2016', 'Italian Serie A')
italy_1617 = create_league_table(ita_1617, '2016/2017', 'Italian Serie A')
italy_1718 = create_league_table(ita_1718, '2017/2018', 'Italian Serie A')
italy_tables = pd.concat([italy_1011, italy_1112, italy_1213, italy_1314, italy_1415, italy_1516,
                           italy_1617, italy_1718])
italy_tables.head()

    0  1   2        3   4     season      league_name
0 NaN  1 NaN    Milan  82  2010/2011  Italian Serie A
1 NaN  2 NaN    Inter  76  2010/2011  Italian Serie A
2 NaN  3 NaN   Napoli  70  2010/2011  Italian Serie A
3 NaN  4 NaN  Udinese  66  2010/2011  Italian Serie A
4 NaN  5 NaN    Lazio  66  2010/2011  Italian Serie A

In [16]:
def create_italian_outlier(url_base, season_years, league_name):
    result_code = requests.get(url_base)
    soup_code = bs(result_code.content)
    league_table = pd.read_html(str(soup_code))[10]
    league_table['season'] = season_years
    league_table['league_name'] = league_name
    return(league_table)

In [17]:
italy_1819 = create_italian_outlier(ita_1819, '2018/2019', 'Italian Serie A')
italy_tables = pd.concat([italy_tables, italy_1819])
italy_tables.tail()

     0   1   2           3   4     season      league_name
15 NaN  16 NaN  Fiorentina  41  2018/2019  Italian Serie A
16 NaN  17 NaN       Genoa  38  2018/2019  Italian Serie A
17 NaN  18 NaN      Empoli  38  2018/2019  Italian Serie A
18 NaN  19 NaN   Frosinone  25  2018/2019  Italian Serie A
19 NaN  20 NaN      Chievo  17  2018/2019  Italian Serie A

In [18]:
spain_1011 = create_league_table(spa_1011, '2010/2011', 'Spanish La Liga')
spain_1112 = create_league_table(spa_1112, '2011/2012', 'Spanish La Liga')
spain_1213 = create_league_table(spa_1213, '2012/2013', 'Spanish La Liga')
spain_1314 = create_league_table(spa_1314, '2013/2014', 'Spanish La Liga')
spain_1415 = create_league_table(spa_1415, '2014/2015', 'Spanish La Liga')
spain_1516 = create_league_table(spa_1516, '2015/2016', 'Spanish La Liga')
spain_1617 = create_league_table(spa_1617, '2016/2017', 'Spanish La Liga')
spain_1718 = create_league_table(spa_1718, '2017/2018', 'Spanish La Liga')
spain_1819 = create_league_table(spa_1819, '2018/2019', 'Spanish La Liga')
spain_tables = pd.concat([spain_1011, spain_1112, spain_1213, spain_1314, spain_1415, spain_1516,
                           spain_1617, spain_1718, spain_1819])
spain_tables.head()

    0  1   2            3   4     season      league_name
0 NaN  1 NaN    Barcelona  96  2010/2011  Spanish La Liga
1 NaN  2 NaN  Real Madrid  92  2010/2011  Spanish La Liga
2 NaN  3 NaN     Valencia  71  2010/2011  Spanish La Liga
3 NaN  4 NaN   Villarreal  62  2010/2011  Spanish La Liga
4 NaN  5 NaN      Sevilla  58  2010/2011  Spanish La Liga

In [19]:
league_tables = pd.concat([england_tables, france_tables, germany_tables, italy_tables, spain_tables])
league_tables = league_tables.reset_index(drop=True)
league_tables.head()

    0  1   2                  3   4     season             league_name
0 NaN  1 NaN  Manchester United  80  2010/2011  English Premier League
1 NaN  2 NaN            Chelsea  71  2010/2011  English Premier League
2 NaN  3 NaN    Manchester City  71  2010/2011  English Premier League
3 NaN  4 NaN            Arsenal  68  2010/2011  English Premier League
4 NaN  5 NaN  Tottenham Hotspur  62  2010/2011  English Premier League

In [20]:
league_tables = league_tables.drop(columns = [0,2])
league_tables.head()

   1                  3   4     season             league_name
0  1  Manchester United  80  2010/2011  English Premier League
1  2            Chelsea  71  2010/2011  English Premier League
2  3    Manchester City  71  2010/2011  English Premier League
3  4            Arsenal  68  2010/2011  English Premier League
4  5  Tottenham Hotspur  62  2010/2011  English Premier League

In [21]:
league_tables = league_tables.rename(columns={1:'finish', 3:'team_name', 4:'points'})
league_tables.head()

   finish          team_name  points     season             league_name
0       1  Manchester United      80  2010/2011  English Premier League
1       2            Chelsea      71  2010/2011  English Premier League
2       3    Manchester City      71  2010/2011  English Premier League
3       4            Arsenal      68  2010/2011  English Premier League
4       5  Tottenham Hotspur      62  2010/2011  English Premier League

In [22]:
league_tables = league_tables[['season', 'league_name', 'finish', 'team_name', 'points']]
league_tables.tail()

        season      league_name  finish       team_name  points
877  2018/2019  Spanish La Liga      16      Valladolid      41
878  2018/2019  Spanish La Liga      17      Celta Vigo      41
879  2018/2019  Spanish La Liga      18          Girona      37
880  2018/2019  Spanish La Liga      19          Huesca      33
881  2018/2019  Spanish La Liga      20  Rayo Vallecano      32

In [23]:
league_tables.team_name = league_tables.team_name.str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [24]:
league_tables.team_name = league_tables.team_name.replace({'Manchester United':'Man United','Manchester City':'Man City',
       'Tottenham Hotspur':'Tottenham','WBA':'West Brom', 'Newcastle United':'Newcastle',
       'Stoke City':'Stoke', 'Bolton Wanderers':'Bolton', 'Blackburn Rovers':'Blackburn',
       'Wigan Athletic':'Wigan', 'Birmingham City':'Birmingham',
       'West Ham United':'West Ham', 'Swansea City':'Swansea', 'Norwich City':'Norwich',
        'Hull City':'Hull','Cardiff City':'Cardiff', 'Leicester City':'Leicester','Brighton & HA':'Brighton',
       'Huddersfield Town':'Huddersfield', 
})

In [25]:
league_tables.team_name = league_tables.team_name.replace({
       'Saint-Etienne':'St Etienne','Evian TG FC':'Evian',
       'GFC Ajaccio':'Ajaccio GFCO'})

In [26]:
league_tables.team_name = league_tables.team_name.replace({'Borussia Dortmund':'Dortmund', 'Bayer Leverkusen':'Leverkusen',
       'Bayern Munchen':'Bayern Munich', 'Hannover 96':'Hannover', 'FSV Mainz 05':'Mainz', '1.FC Nurnberg':'Nurnberg',
       'Hamburger SV':'Hamburg', 'SC Freiburg':'Freiburg', '1.FC Koln':'FC Koln',
       'TSG Hoffenheim':'Hoffenheim', 'VfB Stuttgart':'Stuttgart', 'SV Werder Bremen':'Werder Bremen',
       'FC Schalke 04':'Schalke 04', 'VfL Wolfsburg':'Wolfsburg', 'Borussia Monchengladbach':'B Monchengladbach',
       'Eintracht Frankfurt':'Ein Frankfurt', 'St.Pauli':'St Pauli', 'FC Augsburg':'Augsburg',
       'Hertha BSC Berlin':'Hertha Berlin', 'Fortuna Dusseldorf':'Fortuna Dusseldorf',
       'Eintracht Braunschweig':'Braunschweig', 'SC Paderborn 07':'Paderborn', 'FC Ingolstadt':'Ingolstadt',
       'SV Darmstadt 98':'Darmstadt'
})

In [27]:
league_tables.team_name = league_tables.team_name.replace({'Milan':'AC Milan', 'Inter':'Inter Milan','Cesena (old)':'Cesena',
       'Robur Siena':'Siena'
})

In [28]:
league_tables.team_name = league_tables.team_name.replace({'Athletic Bilbao':'Ath Bilbao', 'Atletico Madrid':'Ath Madrid', 
'Espanyol':'RCD Espanyol','Sporting Gijon':'Sp Gijon','Racing Santander':'Santander',
'Real Sociedad':'Sociedad',
'Deportivo':'La Coruna','Real Betis':'Betis', 'Rayo Vallecano':'Vallecano',
'Celta Vigo':'Celta'})

In [29]:
league_tables = league_tables.sort_values(by=['season', 'league_name', 'finish'])
league_tables = league_tables.reset_index(drop=True)
league_tables.head()

      season             league_name  finish   team_name  points
0  2010/2011  English Premier League       1  Man United      80
1  2010/2011  English Premier League       2     Chelsea      71
2  2010/2011  English Premier League       3    Man City      71
3  2010/2011  English Premier League       4     Arsenal      68
4  2010/2011  English Premier League       5   Tottenham      62

In [30]:
league_tables.to_csv('data/league_tables.csv', index = False)

In [31]:
league_tables.to_excel("data/league_tables_data.xlsx", sheet_name='league_table_data', index = False)